version: "2"
services:
    node6:
        image: "node:6"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - DBWEBB_PORT=8060
        volumes:
            - ./:/home/node/app
        ports:
            - "8060:8060"
        command: "npm start"


    node8:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - DBWEBB_PORT=8080
        volumes:
            - ./:/home/node/app
        ports:
            - "8080:8080"
        command: "npm start"

    node9:
        image: "node:9"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - DBWEBB_PORT=8090
        volumes:
            - ./:/home/node/app
        ports:
            - "8090:8090"
        command: "npm start"
